# Generated by Django 5.2.6 on 2025-09-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.TextField()),
                ('publishers', models.TextField()),
                ('publish_date', models.CharField(max_length=50)),
                ('cover', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
